# Generated by Django 4.2.11 on 2024-10-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_twoFactor',
            field=models.BooleanField(default=False),
        ),
    ]
