# Generated by Django 4.2.11 on 2024-10-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_totp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='totp',
        ),
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
