# Generated by Django 4.2.11 on 2024-10-09 11:44

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_totp_user_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(default=pyotp.random_base32, max_length=16),
        ),
    ]
