# Generated by Django 5.1.2 on 2024-10-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_tmp_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='totp_secret',
        ),
    ]
