
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: koki
      POSTGRES_PASSWORD: 123456789
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - 5432:5432
  client-service:
    build: ./client
    container_name: client-service
    volumes:
      - "./client:/usr/share/nginx/html"
      # - "./nginx/nginx.conf:/etc/nginx/nginx.conf"/
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - home-service
      - db
    networks:
      - app_network
      
  auth-service:
    build: ./server/auth_service
    container_name: auth-service
    ports:
        - "8000:8000"
    networks:
      - app_network
    depends_on:
      - db
  home-service:
    build: ./server/home_service
    container_name: home-service
    networks:
      - app_network
    ports:
      - "8001:8001"
    depends_on:
      - db
  
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
