# Generated by Django 4.2.16 on 2024-10-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0002_tournament_player_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='./ft_transcendence/frontend/assets/images/gold.png', upload_to='./ft_transcendence/frontend/assets/images'),
        ),
    ]
