# Generated by Django 4.2.16 on 2024-10-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_images/gold.png', upload_to='player_images/'),
        ),
    ]
