# Generated by Django 4.2.16 on 2024-10-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_alter_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_image',
            field=models.ImageField(blank=True, null=True, upload_to='match_images/'),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_image',
            field=models.ImageField(blank=True, null=True, upload_to='match_images/'),
        ),
    ]
