# Generated by Django 4.2.16 on 2024-10-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_match_player1_image_match_player2_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1_image',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_image',
        ),
    ]
