# Generated by Django 4.2.16 on 2024-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_remove_match_player1_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_images/avatar_pic', upload_to='player_images/'),
        ),
    ]
