# Generated by Django 4.2.16 on 2024-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_alter_player_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_images/avatar_pic.png', upload_to='player_images/'),
        ),
    ]
