# Generated by Django 4.2.16 on 2024-11-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0009_alter_player_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
    ]
