# Generated by Django 5.1.2 on 2024-10-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_privatemessage_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
