# Generated by Django 5.1.2 on 2024-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='roomName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
