# Generated by Django 5.1.2 on 2024-11-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_privatemessage_roomname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatemessage',
            name='roomName',
        ),
    ]
