# Generated by Django 5.1.2 on 2024-11-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_privatemessage_roomname'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='roomName',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
