# Generated by Django 4.2.18 on 2025-01-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='user_pics/default.png', null=True, upload_to='user_pics/'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='PlayerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_locked', to='user_service.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='user_service.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='user_service.player'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_to', to='user_service.user'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_from', to='user_service.user'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_service.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='user_service.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_request', to='user_service.user'),
        ),
    ]
