# Generated by Django 4.2.19 on 2025-02-19 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('local', 'Local')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_service.user'),
        ),
    ]
