# Generated by Django 4.2.19 on 2025-02-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('local', 'Local')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='user_service.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='user_service.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('exited', 'Exited')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playertournament',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Online_Notification',
        ),
    ]
