# Generated by Django 4.2.19 on 2025-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_match_player1_nickname_match_player2_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
