# Generated by Django 4.2.18 on 2025-01-21 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator(message='Age must be a valid positive number.', regex='^\\d+$')]),
        ),
    ]
