# Generated by Django 4.2.19 on 2025-03-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0003_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
