# Generated by Django 4.2.18 on 2025-01-27 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0004_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z_\\-\\r ]*$', 'Only alphabetic characters, underscores, hyphens, carriage returns, and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z_\\-\\r ]*$', 'Only alphabetic characters, underscores, hyphens, carriage returns, and spaces are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='users_pics/default.png', null=True, upload_to='users_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator('^[a-zA-Z0-9!@#$%^&*()_+=\\-\\[\\]{};:\\\'",.<>?/|\\\\`~ \\t\\n\\r]*$', 'Only alphabetic, numeric, special characters, and whitespace are allowed.')]),
        ),
    ]
