# Generated by Django 4.2.19 on 2025-03-03 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0004_remove_user_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.CharField(blank=True, default='Newbie', max_length=50, null=True),
        ),
    ]
