# Generated by Django 4.2.19 on 2025-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_match_created_at_player_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
