# Generated by Django 4.2.19 on 2025-02-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0008_tournament_mode_alter_match_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertournament',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
