# Generated by Django 4.2.19 on 2025-02-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0011_remove_match_player2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
