# Generated by Django 4.2.17 on 2024-12-20 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertournament',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='player_images/'),
        ),
        migrations.AlterField(
            model_name='playertournament',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(blank=True, max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
