# Generated by Django 4.2.18 on 2025-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='room_name',
            field=models.CharField(max_length=50),
        ),
    ]
