# Generated by Django 4.2.17 on 2025-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='test',
            new_name='refresh_token',
        ),
        migrations.AddField(
            model_name='user',
            name='enabled_twoFactor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
