# Generated by Django 4.2.17 on 2025-01-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
    ]
