# Generated by Django 4.2.19 on 2025-02-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
