# Generated by Django 4.2.19 on 2025-02-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_user_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='test',
        ),
    ]
