# Generated by Django 4.2.19 on 2025-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='grade',
            field=models.CharField(blank=True, default='Newbie', max_length=50, null=True),
        ),
    ]
