# Generated by Django 4.2.19 on 2025-02-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_playertournament_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
