# Generated by Django 4.2.19 on 2025-02-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_tournament_mode_alter_player_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='Online_Notification',
        ),
    ]
