# Generated by Django 4.2.19 on 2025-02-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0005_alter_match_player1_alter_match_player2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='mode',
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='matchmaking.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='matchmaking.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmaking.user'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Notification',
        ),
    ]
