# Generated by Django 4.2.19 on 2025-02-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0008_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('online', 'Online'), ('local', 'Local')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='match',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to='matchmaking.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to='matchmaking.player'),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='Online_Notification',
        ),
    ]
