# Generated by Django 4.2.19 on 2025-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_match_player1_nickname_match_player2_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='player1_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='player2_nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
