
export const translations = {
    en: {
        Friends: "Friends",
        Pending: "Pending",
        Requests: "Requests",
        Achievements: "Achievements",
        "Winning rate": "Winning rate",
        "Matches history": "Matches history",
        Win: "Win",
        Loss: "Loss",
        "View all": "View all",
        Training: "Training",
        PLAY: "PLAY",
        Tournament: "Tournament",
        "Lets Play": "Lets Play",
        "First name": "First name",
        "Last name": "Last name",
        Username: "Username",
        Age: "Age",
        "Phone number": "Phone number",
        Nationality: "Nationality",
        "E-mail": "E-mail",
        Gender: "Gender",
        Submit : 'Submit',
        Male:'Male',
        Female:'Female',
        Score:'Score',
        Rank: 'Rank',
        Leaderboard:'Leaderboard',
        Name : 'Name',
        Level : 'Level',
        Badge : 'Badge',
        Home: 'Home',
        'About':'About',
        'Our Team':'Our Team', 
        'Join Now':'Join Now',
        dive: "Dive into our",
        universe: "universe!",
        pingpong: "ping pong",
        welcome: "Welcome to your ultimate ping pong playground! Get ready to smash your way to victory.",
        experience: "Whether you're a seasoned player or just starting out, let's bounce into action together.",
        about_us: "ABOUT US",

        welcome: "Welcome to our website, we designed this website as a final project for our",
        school: "school 1337, where the excitement of ping pong meets a vibrant community",
        experience: "experience. Dive into thrilling matches, connect with fellow players through",
        chat: "dynamic chatroom, and track your achievements as you climb the leaderboard",
        beginner: "Whether you're a seasoned competitor or new to the game, our website",
        goal: "is your go-to destination for enjoying and improving your ping pong skills",
        atmosphere: "in a friendly and competitive atmosphere. Join us today and discover",
        thrill: "the thrill of ping pong like never before!",

        "TEAM_HEADER": "The team",
        "magic":"behind the magic",
        "TEAM_LINE_1": "Our developers work tirelessly to bring the ping pong website to life,",
        "TEAM_LINE_2": "ensuring every user enjoys a seamless and unforgettable experience.",
        "TEAM_LINE_3": "Meet the team behind the magic!",
        "security_message" : "Enhance your security with Two-Factor Authentication (2FA).\nThis robust security measure adds an extra layer of protection\nto your account by requiring two forms of verification before \ngranting access.",
        
        "two_factor_label" : "Two-factor authentication 2FA:",
        enable  : "Enable",
        informations : 'Informations',

        blocked_friends: "Blocked friends",
        security: 'Security',
        "password_title" :  "Password:",

        "current_password_placeholder": "Current password",
            
        "new_password_placeholder": "New password",
           
        "confirm_password_placeholder":  "Confirm password",
            
        "change_button": "Change",
            


    },
    fr: {
        Friends: "Amis",
        Pending: "En attente",
        Requests: "Invitations",
        Achievements: "Réalisations",
        "Winning rate": "Taux de victoire",
        "Matches history": "Historique des matchs",
        Win: "Victoire",
        Loss: "Défaite",
        "View all": "Voir tout",
        Training: "Entraînement",
        PLAY: "Jouer",
        Tournament: "Tournoi",
        "Lets Play": "Jouons",
        "First name": "Prénom",
        "Last name": "Nom",
        Username: "Nom d'utilisateur",
        Age: "Âge",
        "Phone number": "Numéro de téléphone",
        Nationality: "Nationalité",
        "E-mail": "E-mail",
        Gender: "Genre",
        Submit : 'Soumettre',
        Male:'Homme',
        Female:'Femme',
        Score:'Score',
        Rank: 'Classement',
        Leaderboard:'Classement',
        Name : 'Nom',
        Level : 'Niveau',
        Badge : 'Badge',
        Home: 'Accueil',
        'About':'À propos',
        'Our Team':'Notre équipe',
        'Join Now':'Rejoignez-nous maintenant',
        dive: "Plongez dans notre",
        universe: "univers!",
        pingpong: "ping-pong",
        welcome: "Bienvenue sur votre terrain de jeu ultime de ping-pong ! Préparez-vous à frapper votre chemin vers la victoire.",
        experience: "Que vous soyez un joueur expérimenté ou que vous commenciez tout juste, lançons-nous ensemble dans l'action.",
        about_us: "À PROPOS DE NOUS",

        welcome: "Bienvenue sur notre site web, nous avons conçu ce site comme un projet final pour notre",
        school: "école 1337, où l'excitation du ping-pong rencontre une communauté dynamique",
        experience: "Plongez dans des matchs palpitants, connectez-vous avec d'autres joueurs via",
        chat: "une salle de chat dynamique et suivez vos progrès en grimpant dans le classement",
        beginner: "Que vous soyez un compétiteur expérimenté ou nouveau dans le jeu, notre site",
        goal: "est votre destination idéale pour profiter et améliorer vos compétences en ping-pong",
        atmosphere: "dans une ambiance conviviale et compétitive. Rejoignez-nous dès aujourd'hui et découvrez",
        thrill: "le frisson du ping-pong comme jamais auparavant !",

        
        
        "TEAM_HEADER": "L'équipe",
        
        "magic":"derrière la magie",
        "TEAM_LINE_1": "Nos développeurs travaillent sans relâche pour donner vie au site de ping-pong,",
        "TEAM_LINE_2": "garantissant à chaque utilisateur une expérience fluide et inoubliable.",
        "TEAM_LINE_3": "Rencontrez l'équipe derrière la magie !",

        "security_message" : "Renforcez votre sécurité avec l'authentification à deux facteurs (2FA).\nCette mesure de sécurité robuste ajoute une couche de protection supplémentaire\nà votre compte en exigeant deux formes de vérification avant \nd'accorder l'accès.",
        
        "two_factor_label" : "Authentification à deux facteurs (2FA) :",
        enable :  "Activer",

        informations : 'Informations',
        blocked_friends : "Amis bloqués",
        security: "Sécurité",
        "password_title": "Mot de passe :",

        "current_password_placeholder": "Mot de passe actuel",
           
        "new_password_placeholder": "Nouveau mot de passe",
          
        "confirm_password_placeholder": "Confirmer le mot de passe",
          
        "change_button":"Changer",

    },
    ar: {
        Friends: "أصدقاء",
        Pending: "قيد الانتظار",
        Requests: "طلبات",
        Achievements: "الإنجازات",
        "Winning rate": "معدل الفوز",
        "Matches history": "تاريخ المباريات",
        Win: "فوز",
        Loss: "خسارة",
        "View all": "عرض الكل",
        Training: "تدريب",
        PLAY: "اللعب",
        Tournament: "بطولة",
        "Lets Play": "لنلعب",
        "First name": "الاسم الأول",
        "Last name": "الاسم الأخير",
        Username: "اسم المستخدم",
        Age: "العمر",
        "Phone number": "رقم الهاتف",
        Nationality: "الجنسية",
        "E-mail": "البريد الإلكتروني",
        Gender: "الجنس",
        Submit:'إرسال',
        Male:'ذكر',
        Female:'أنثى',
        Score:'النقاط',
        Rank: 'الترتيب',
        Leaderboard:'الترتيب',
        Name : 'الاسم',
        Level : 'المستوى',
        Badge : 'شارة',
        Home: 'الصفحة الرئيسية',
        'About':'حول',
        'Our Team': 'فريقنا',
        'Join Now': 'انضم الآن',
        dive: "اغمر نفسك في",
        universe: "عالمنا!",
        pingpong: "بينغ بونغ",
        welcome: "مرحبًا بك في ملعبك النهائي لتنس الطاولة! استعد لتسديد طريقك نحو النصر",
        experience: "سواء كنت لاعبًا متمرسًا أو بدأت للتو، لننطلق معًا في الحدث",
        
        about_us: "معلومات عنا",
        welcome: "مرحبًا بك في موقعنا الإلكتروني، لقد صممنا هذا الموقع كمشروع نهائي لمدرستنا",
        school: "مدرسة 1337، حيث يلتقي حماس تنس الطاولة بمجتمع حيوي",
        experience: "انغمس في مباريات مثيرة، تواصل مع لاعبين آخرين من خلال",
        chat: "غرفة دردشة ديناميكية، وتابع إنجازاتك أثناء تسلقك لوحة المتصدرين",
        beginner: "سواء كنت منافسًا متمرسًا أو جديدًا في اللعبة، فإن موقعنا",
        goal: "هو وجهتك المثالية للاستمتاع وتحسين مهاراتك في تنس الطاولة",
        atmosphere: "في جو ودي وتنافسي. انضم إلينا اليوم واكتشف",
        thrill: "إثارة تنس الطاولة كما لم تعشها من قبل!",

        "TEAM_HEADER": "الفريق",
        "magic": "وراء السحر",
        "TEAM_LINE_1": "يعمل مطورونا بلا كلل لإحياء موقع تنس الطاولة،",
        "TEAM_LINE_2": "مما يضمن لكل مستخدم تجربة سلسة ولا تُنسى.",
        "TEAM_LINE_3": "تعرف على الفريق الذي يقف وراء السحر!",

        "security_message" : "عزز أمانك باستخدام المصادقة الثنائية (2FA).\nتضيف هذه التدابير الأمنية القوية طبقة إضافية من الحماية\nلحسابك من خلال طلب شكلين من التحقق قبل \nمنح الوصول.",
        
        "two_factor_label"  : "المصادقة الثنائية (2FA):",

        enable : "تفعيل",

        informations : 'معلومات',
        blocked_friends: "الأصدقاء المحظورون",
        security : 'الأمان',
        "password_title": "كلمة المرور:",

        "current_password_placeholder": "كلمة المرور الحالية",

        "new_password_placeholder": "كلمة المرور الجديدة",
        "confirm_password_placeholder":  "تأكيد كلمة المرور",
        "change_button": "تغيير"

    }
};
