# Generated by Django 4.2.18 on 2025-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('information', 'information'), ('request', 'Request'), ('invitation', 'Invitation'), ('accepted', 'Accepted')], max_length=100),
        ),
    ]
