# Generated by Django 4.2.18 on 2025-01-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_alter_playertournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=50),
        ),
    ]
