# Generated by Django 4.2.19 on 2025-02-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
