# Generated by Django 4.2.19 on 2025-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_match_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('tournament', 'Tournament'), ('enter_tournament', 'enter_tournament'), ('information', 'information'), ('request', 'Request'), ('invitation', 'Invitation'), ('accepted', 'Accepted')], max_length=100),
        ),
    ]
