# Generated by Django 4.2.19 on 2025-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_player_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
