# Generated by Django 4.2.11 on 2024-10-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_enabled_twofactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
