# Generated by Django 4.2.20 on 2025-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_match_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playertournament',
            name='avatar',
            field=models.ImageField(blank=True, default='player_images/default.png', null=True, upload_to='player_images/'),
        ),
    ]
