# Generated by Django 4.2.19 on 2025-02-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_tournament_mode_alter_match_player1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
