# Generated by Django 4.2.19 on 2025-02-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_player_level_alter_player_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('completed', 'Completed'), ('exited', 'Exited')], default='pending', max_length=10),
        ),
    ]
