# Generated by Django 4.2.11 on 2024-10-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_user_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
