# Generated by Django 5.1.2 on 2024-10-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
