# Generated by Django 5.1.2 on 2024-11-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_remove_user_qr_code_remove_user_totp_secret"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Player",
        ),
    ]
