# Generated by Django 4.2.17 on 2024-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_twoFactor',
            field=models.BooleanField(default=False),
        ),
    ]
