# Generated by Django 4.2.16 on 2024-10-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player_id1',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='player_id2',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='point_opponent',
            new_name='point_player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='point_player',
            new_name='point_player2',
        ),
    ]
