# Generated by Django 5.1.2 on 2024-12-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
