# Generated by Django 4.2.16 on 2024-10-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_rename_player_id1_match_player1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='point_player1',
            new_name='player1_points',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='point_player2',
            new_name='player2_points',
        ),
    ]
