# Generated by Django 5.1.2 on 2024-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Sent"),
                    ("received", "Received"),
                    ("accepted", "Accepted"),
                    ("blocked", "Blocked"),
                ],
                max_length=255,
            ),
        ),
    ]
