# Generated by Django 5.1.2 on 2024-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0003_alter_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("blocked", "Blocked"),
                    ("pending", "Pending"),
                ],
                max_length=255,
            ),
        ),
    ]
