# Generated by Django 4.2.16 on 2024-10-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_point_player1_match_player1_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='notif_from', to='Profile.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='reciever',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_to', to='Profile.user'),
        ),
    ]
