# Generated by Django 5.1.2 on 2024-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0004_alter_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nationality",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
