# Generated by Django 5.1.2 on 2024-12-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0005_alter_user_email_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.BooleanField(null=True),
        ),
    ]
